apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: svc-node
  name: nodeport-test-pod
spec:
  containers:
  - image: nginx
    name: nodeport-test-pod
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
